#!/bin/sh

case "$1" in
  start)
    echo "Checking for first boot flag and starting first_boot_config if YES"
    /usr/bin/first_boot_config
    ;;
  stop)
    echo "stopping first_boot_monitor"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit $?
