#!/bin/sh

echo "Starting WPA Supplicant and udhcpc..."

# Fire up wpa_supplicant
wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf

#give it time to associate, etc
sleep 5

# get an IP
udhcpc -i wlan0
