#!/bin/sh

case "$1" in
  start)
    echo "Setting gain on all devices to 0db"
    /usr/bin/set_alsa_gain
    ;;
  stop)
    echo "stopping set_volume"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit $?
